// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXbUs6LbEVWDWwGqa5btOhVmgthxm3aA',
    appId: '1:463927330373:ios:1837190954d16f2b50c52c',
    messagingSenderId: '463927330373',
    projectId: 'residential-management-s-2217c',
    databaseURL: 'https://residential-management-s-2217c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'residential-management-s-2217c.appspot.com',
    iosBundleId: 'com.example.residentialManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXbUs6LbEVWDWwGqa5btOhVmgthxm3aA',
    appId: '1:463927330373:ios:1837190954d16f2b50c52c',
    messagingSenderId: '463927330373',
    projectId: 'residential-management-s-2217c',
    databaseURL: 'https://residential-management-s-2217c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'residential-management-s-2217c.appspot.com',
    iosBundleId: 'com.example.residentialManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARqhfmeBszgBRqzvCXXDTmCo2kP_EC5Oc',
    appId: '1:463927330373:web:29ad1143db55e92e50c52c',
    messagingSenderId: '463927330373',
    projectId: 'residential-management-s-2217c',
    authDomain: 'residential-management-s-2217c.firebaseapp.com',
    databaseURL: 'https://residential-management-s-2217c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'residential-management-s-2217c.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqhfmeBszgBRqzvCXXDTmCo2kP_EC5Oc',
    appId: '1:463927330373:web:29ad1143db55e92e50c52c',
    messagingSenderId: '463927330373',
    projectId: 'residential-management-s-2217c',
    authDomain: 'residential-management-s-2217c.firebaseapp.com',
    databaseURL: 'https://residential-management-s-2217c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'residential-management-s-2217c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfUpH_HUxrCL3HyfjvzE0ToQFqM1Sgh4U',
    appId: '1:463927330373:android:c018e74887b1ef4c50c52c',
    messagingSenderId: '463927330373',
    projectId: 'residential-management-s-2217c',
    databaseURL: 'https://residential-management-s-2217c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'residential-management-s-2217c.appspot.com',
  );

}